In [1]:
import logging
import numpy as np
import pandas as pd 
import scipy.io
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = scipy.io.loadmat("arrhythmia.mat")

In [3]:
features = data["X"]
labels = data['y']

In [4]:
print(features)

[[ 75.    0.  190.  ...   2.9  23.3  49.4]
 [ 56.    1.  165.  ...   2.1  20.4  38.8]
 [ 54.    0.  172.  ...   3.4  12.3  49. ]
 ...
 [ 36.    0.  166.  ...   1.  -44.2 -33.2]
 [ 32.    1.  155.  ...   2.4  25.   46.6]
 [ 78.    1.  160.  ...   1.6  21.3  32.8]]


In [5]:
scaler = MinMaxScaler()
scaler.fit(features)
features =  scaler.transform(features)

In [6]:
print (features)

[[0.90361446 0.         0.12592593 ... 0.74166667 0.5075188  0.56957929]
 [0.6746988  1.         0.08888889 ... 0.675      0.48571429 0.50097087]
 [0.65060241 0.         0.09925926 ... 0.78333333 0.42481203 0.56699029]
 ...
 [0.43373494 0.         0.09037037 ... 0.58333333 0.         0.03495146]
 [0.38554217 1.         0.07407407 ... 0.7        0.52030075 0.55145631]
 [0.93975904 1.         0.08148148 ... 0.63333333 0.4924812  0.46213592]]


In [7]:
print (sum(labels==0))
print (sum(labels==1))

[386]
[66]


In [8]:
data = np.concatenate((features, labels),axis=1)

In [9]:
np.save('Arrhythmia',data)